---
global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
scrape_configs:
  - job_name: "prometheus"
    honor_timestamps: true
    scrape_interval: "15s"
    scrape_timeout: "10s"
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: "exported-metrics-from-[permission-system]"
    metrics_path: "/api/v1alpha/metrics"
    basic_auth:
      username: "[permission-system]"
      password: "[token]"
    static_configs:
      - targets:
          - "[authzed-dashboard-url]"
